---
- name: Disable SSH password authentication
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication\s'
    line: 'PasswordAuthentication no'
    state: present
  notify:
    - Restart SSH service
    - Restart instance
