---
# tasks file for roles/install_docker
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  loop:
    - nginx
    - docker.io
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Start Docker service
  ansible.builtin.service:
    name: "{{item}}"
    state: started
    enabled: true
  loop:
    - docker
    - nginx
